# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ad5f0b3da22c9534dae901311c1ad52772d520338674fa1aaf333dd676bd983230740be8a9e6e218b2a49d333d04a28ba334946b7d5cb478a6555b9d4bfbc02

test:
  secret_key_base: 0caaa7e97347369b8fe67247993074aecdb2a278b92cf297d5dcb0e980bae30acf72d729d4ef7ca93930bed90124f0a064c630f449acace4010d713e8ae93ea4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
